### ISSUE TITLE
ImportError when launching MCF_Blum module

### ISSUE THREAD

**Issue by vedma1337** [masterking32/MCF_Blum#13]
Ubuntu 22.04, python 3.10,
![image](https://github.com/user-attachments/assets/02b49b21-fdfb-4245-9ebb-88b943578043)

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/usr/local/lib/python3.10/dist-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MasterCryptoFarmBot/modules/MCF_Blum/bot.py", line 18, in <module>
    from FarmBot.FarmBot import FarmBot
  File "/root/MasterCryptoFarmBot/modules/MCF_Blum/FarmBot/FarmBot.py", line 12, in <module>
    from .core.HttpRequest import HttpRequest
  File "/root/MasterCryptoFarmBot/modules/MCF_Blum/FarmBot/core/HttpRequest.py", line 8, in <module>
    import cloudscraper
  File "/usr/local/lib/python3.10/dist-packages/cloudscraper/__init__.py", line 10, in <module>
    from requests_toolbelt.utils import dump
  File "/usr/lib/python3/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/local/lib/python3.10/dist-packages/urllib3/contrib/__init__.py)
```

**Comment by Fy0urM** [comment]
try to reinstall this modules manually
requests urllib3 requests-toolbelt cloudscraper

**Comment by vedma1337** [comment]
> try to reinstall this libs manually requests urllib3 requests-toolbelt cloudscraper

didn't help, still can't import

**Comment by masterking32** [comment]
`pip install --force-reinstall requests urllib3 requests-toolbelt cloudscraper`

**Comment by vedma1337** [comment]
> `pip install --force-reinstall requests urllib3 requests-toolbelt cloudscraper`

Thank you, it worked
